MegaRedHand/network-simulator

.github/workflows/ci.yml, package-lock.json, package.json, src/packets/icmp.ts, src/packets/ip.ts, test/ip.test.ts
This PR adds new modules with IP and ICMP packet implementations, along with jest integration to start adding unit tests.
=> feat: add IP & ICMP packet implementations

src/index.ejs, src/types/device.ts, src/types/edge.ts, src/types/networkgraph.ts, src/types/packet.ts
=> feat: add packet animation along a path

src/types/devices/device.ts
Reverts MegaRedHand/network-simulator#39
=> Revert "fix: device is selected while dragging"

src/index.ts, src/types/devices/device.ts
- The device get selected immediately when start being dragged.
- refactor + perf*: functions for dragging logic in Device are only called when device is being actually dragged.
=> Select dragging device

src/graphics/renderables/device_info.ts, src/types/devices/device.ts, src/types/devices/router.ts, src/types/graphs/datagraph.ts, src/types/graphs/viewgraph.ts, src/types/packet.ts
This PR adds packet data to `Packet`, and shows part of that info in the right bar.
=> feat: show IP addresses in packet info

src/index.ts
This PR turns on antialiasing on the PixiJS renderer.
Before:
After:
=> feat: add antialias

package-lock.json, package.json, src/types/packet.ts
=> feat: delete packet button

src/graphics/renderables/device_info.ts, src/types/devices/host.ts, src/types/devices/router.ts
=> feat!: make router unable to send packets

src/context.ts, src/index.ts, src/types/devices/utils.ts, src/types/graphs/viewgraph.ts, src/types/viewportManager.ts
This PR makes it so the current layer is persisted between sessions in local storage.
=> feat: persist layer selection

src/context.ts, src/graphics/left_bar.ts, src/index.ts, src/types/devices/device.ts, src/types/devices/host.ts, src/types/devices/layer.ts, src/types/devices/utils.ts, src/types/graphs/viewgraph.ts, src/types/viewportManager.ts
This PR moves some initialization code from `src/index.ts` to `LeftBar`.
=> refactor: move initialization to left bar

src/context.ts, src/graphics/renderables/device_info.ts, src/index.ts, src/types/devices/device.ts, src/types/devices/host.ts, src/types/devices/utils.ts, src/types/graphs/datagraph.ts, src/types/graphs/viewgraph.ts, src/types/packet.ts, src/types/undo-redo/moves/addRemoveDevice.ts, src/types/undo-redo/moves/addRemoveEdge.ts, src/types/viewportManager.ts
This PR stores the programs running on Hosts inside the datagraph. This makes it persistent between layer changes and sessions.
=> feat: store Host programs in datagraph

src/assets/switch.svg, src/graphics/left_bar.ts, src/graphics/renderables/device_info.ts, src/index.ts, src/types/devices/device.ts, src/types/devices/switch.ts, src/types/devices/utils.ts, src/types/graphs/datagraph.ts
Added the initial implementation of the Switch device with basic functionality. Further development is required to implement switch-specific features.
=> feat: add basic Switch implementation

src/programs/echo_sender.ts
Closes #112
This PR makes the speed slider affect program progress too.
=> feat: make speed multiplier affect programs

src/programs/echo_sender.ts, src/programs/program_base.ts
Closes #90
How it looks now:
The input is a dropdown, but we could move to a slider or text input in the future.
=> feat: configurable ping delay for `EchoServer`

src/types/devices/router.ts
=> fix: Exclude deleted routing table entries from packet forwarding

src/graphics/renderables/device_info.ts, src/graphics/renderables/program_runner_info.ts, src/programs/index.ts, src/types/devices/host.ts
Depends on https://github.com/MegaRedHand/network-simulator/pull/129
This PR refactors the programs list logic to a new ProgramRunnerInfo class and fixes some issues.
=> refactor: move program list styling to ProgramRunnerInfo

src/graphics/right_bar.ts, src/styles/info.css
- Ensured key-value pairs stay on the same line.
- Fixed JSON formatting to prevent overflow.
- Applied CSS tweaks for better alignment and responsiveness.
before:
after:
=> Improved detail and payload rendering in the right sidebar

src/config.ts, src/context.ts, src/index.ejs, src/index.ts, src/styles/config.css, src/styles/help.css, src/styles/index.ts, src/styles/speed-wheel.css, src/styles/top-bar.css, src/types/devices/device.ts, src/types/devices/host.ts, src/types/devices/networkDevice.ts, src/types/devices/router.ts, src/types/devices/switch.ts, src/types/devices/utils.ts, src/types/graphs/viewgraph.ts, src/utils.ts
=> Feat/config menu & shortcuts

src/packets/icmp.ts, src/packets/ip.ts, src/packets/tcp.ts, src/types/devices/router.ts
This PR extracts the packet queue logic into a new class, to avoid breaking its invariants
=> feat: use bytes for packet queue

src/graphics/renderables/program_info.ts, src/programs/echo_sender.ts, src/programs/http_client.ts, src/programs/index.ts, src/types/packet.ts, src/utils.ts
Related to #121
This PR implements an HTTP request program. For now it's just a single TCP packet, but we should come up with a better way to show this.
=> feat: implement HTTP client program

src/graphics/renderables/device_info.ts, src/graphics/renderables/parameter_editor.ts, src/styles/index.ts, src/styles/parameter_editor.css, src/styles/right-bar.css, src/types/data-devices/dRouter.ts, src/types/graphs/datagraph.ts, src/types/graphs/graph.ts, src/types/view-devices/utils.ts, src/types/view-devices/vRouter.ts, src/utils/constants/router_constants.ts, src/utils/constants/tooltips_constants.ts
closes #171 
This pull request introduces several significant changes to enhance the functionality and customization of device parameters in the application. The most important changes include adding parameter groups for devices, updating router settings, and improving the styling of the parameter editor.
Enhancements to device parameters:
* [`src/graphics/renderables/device_info.ts`](diffhunk://#diff-965a7810b34f8fb22a13101c89a873c18aa7d3c9c0dc67f0c79f178859084809R90-R106): Added the `addParameterGroup` method to the `DeviceInfo` class to allow adding groups of parameters with labels, initial values, and change handlers.
* [`src/graphics/renderables/parameter_editor.ts`](diffhunk://#diff-5c7a2451925fba67ae354f6a0c68d0524e89116c28082088712b7b89320b692fR1-R104): Introduced …
=> feat: Make packet queue parameters configurable by the user

src/graphics/renderables/device_info.ts, src/graphics/renderables/progress_bar.ts, src/styles/index.ts, src/styles/progress-bar.css, src/types/data-devices/dRouter.ts, src/types/view-devices/vRouter.ts, src/utils/constants/tooltips_constants.ts
This pull request introduces a new progress bar feature to the `DeviceInfo` class and updates related files to support this functionality. The most important changes include the addition of the `ProgressBar` component, modifications to the `DeviceInfo` class to include the progress bar, and the necessary CSS styles.
* **Progress Bar Component**:
- Added a new `ProgressBar` class in `src/graphics/renderables/progress_bar.ts` to create and manage the progress bar element.
- Introduced `ProgressBarProps` interface to define the properties of the progress bar.
* **DeviceInfo Class Updates**:
- Updated `DeviceInfo` class in `src/graphics/renderables/device_info.ts` to include a method `addProgressBar` for adding a progress bar with a label.
- Imported `ProgressBar` and `TooltipManager` in …
=> feat: Packet Queue Usage Progress Bar

src/graphics/renderables/program_info.ts, src/graphics/right_bar.ts, src/types/edge.ts, src/types/graphs/viewgraph.ts, src/types/view-devices/vDevice.ts
This PR makes viewgraph store all devices, but makes invisible devices not of the current layer (or above).
=> feat: keep edges and hide devices from sub-layers

src/config.ts, src/graphics/basic_components/button.ts, src/graphics/basic_components/dropdown.ts, src/graphics/basic_components/label.ts, src/graphics/basic_components/parameter_editor.ts, src/graphics/basic_components/slider.ts, src/graphics/basic_components/table.ts, src/graphics/basic_components/text_info.ts, src/graphics/basic_components/toggle_button.ts, src/graphics/components/labeled_progress_bar.ts, src/graphics/left_bar.ts, src/graphics/renderables/program_runner_info.ts, src/graphics/renderables/tooltip_manager.ts, src/handlers/pauseHandler.ts, src/handlers/undoRedoHandler.ts, src/index.ts
This pull request refactors the tooltip management system by replacing the `TooltipManager` singleton class with individual functions. The changes involve updating all instances where `TooltipManager` methods were used to use the new functions instead. This refactor aims to simplify the code and improve maintainability.
=> refactor: replace TooltipManager usage with attachTooltip function

src/graphics/renderables/device_info.ts, src/types/data-devices/dSwitch.ts, src/types/edge.ts, src/types/graphs/graph.ts, src/types/graphs/viewgraph.ts
closes #199 
closes #200
closes #208
=> feat: add updateVisibility method to Edge class

src/graphics/renderables/arp_table.ts, src/graphics/renderables/device_info.ts, src/types/data-devices/dNetworkDevice.ts
This pull request introduces a mechanism to dynamically update the ARP table in the UI when changes occur in the underlying data model. The key changes include adding a listener for ARP table updates, implementing a refresh method in the ARP table UI component, and integrating these updates into the `DeviceInfo` class.
=> Dynamic ARP table

src/graphics/basic_components/table.ts, src/graphics/basic_components/text_info.ts, src/graphics/renderables/arp_table.ts, src/graphics/renderables/program_runner_info.ts, src/graphics/renderables/routing_table.ts, src/styles/table.css, src/utils/constants/css_constants.ts
=> fix: wrap tables in scrollable containers

src/handlers/layerSelectorHandler.ts, src/types/edge.ts, src/types/packet.ts, src/types/view-devices/vDevice.ts, src/types/viewportManager.ts
=> Persist selections between layers

src/graphics/renderables/packet_info.ts, src/handlers/layerSelectorHandler.ts, src/types/graphs/viewgraph.ts
=> feat: enhance packet info with device identification (src - dest)

src/config.ts, src/context.ts, src/graphics/renderables/tooltip_manager.ts, src/types/network-modules/tcp/tcpState.ts, src/types/view-devices/vDevice.ts
Closes #222
Depends on #236
This PR allows switching between TCP Reno and Tahoe versions.
=> feat: allow switching between TCP Reno and Tahoe versions

src/graphics/renderables/tooltip_manager.ts
This pull request refactors the tooltip management system in `tooltip_manager.ts` to simplify the logic and improve maintainability. The most significant changes include removing redundant checks for tooltip enablement in multiple functions, updating the `showTooltip` function to accept an `HTMLElement` parameter, and streamlining the tooltip state update process.
* **Simplified `attachTooltip` logic**: Removed the redundant `tooltipsEnabled` check and moved the addition of the `"has-tooltip"` class to the `showTooltip` function. This reduces duplication and ensures consistent behavior.
* **Enhanced mutation observer in `attachTooltip`**: Cleaned up the code for detecting element removal by removing unnecessary conditions and ensuring the observer disconnects after hiding the tooltip.
* …
=> fix: streamline tooltip management and enhance event handling
