MegaRedHand/network-simulator

src/index.ts, src/types/devices/device.ts, src/types/edge.ts, src/types/packet.ts
=> fix: pause packet animation progress

src/index.ejs, src/index.ts, src/style.css, src/types/graphs/datagraph.ts, src/types/graphs/viewgraph.ts, src/types/viewportManager.ts
Using [`localStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) we can save the contents of the graph between restarts.
NOTE: this implementation has concurrency issues when multiple tabs are open.
=> feat: save graph on localStorage

src/index.ts, src/style.css
This update ensures that the auto-save mechanism re-subscribes to changes whenever the graph is replaced.
=> Fix autosave

src/types/packet.ts, src/types/viewportManager.ts
An error is thrown when a packet’s sending process ends with the packet being selected. The error was resolved by deselecting the packet once its sending process is complete.
=> fix: finishing packet sending when packet is selected

src/context.ts, src/graphics/renderables/device_info.ts, src/types/devices/device.ts, src/types/edge.ts, src/types/graphs/datagraph.ts, src/types/graphs/viewgraph.ts, src/types/packet.ts
This PR adds routing table routing.
=> feat: routing through tables

src/graphics/right_bar.ts, src/styles/index.ts, src/styles/info.css, src/types/packet.ts
This pull request introduces new functionality to display detailed information about packets in the right sidebar. The changes include adding a toggle button to show/hide packet details, creating a new function to generate the toggle information, and updating the styles to support the new feature.
Key changes:
**Functionality enhancements:**
* [`src/graphics/right_bar.ts`](diffhunk://#diff-2ffc3b298d27be79ce1fc85f908ca77f488f67ee59e05d3d17b8a9e1aad6d696R77-R90): Added `addToggleButton` method to `RightBar` class to append a toggle button for displaying packet details.
* [`src/graphics/right_bar.ts`](diffhunk://#diff-2ffc3b298d27be79ce1fc85f908ca77f488f67ee59e05d3d17b8a9e1aad6d696R161-R218): Added `createToggleInfo` function to create a container with a toggle button and detailed …
=> Ipv4 header data

src/types/devices/device.ts
Fixed an issue where pressing the connect button again did not cancel the connection process. The `selectToConnect` method now correctly handles connection cancellation by resetting the connection target if it is already set.
Closes #104
=> fix: add device connection cancellation

src/index.ts, src/types/undo-redo/undoRedoManager.ts
Added calls to `deselectElement()` in multiple actions to ensure proper reset of selected elements before performing new operations, improving overall user interaction consistency.
* Select Layer
* New, Load, Save buttons
* Undo Redo
Closes #102
=> feat: add element deselection to various actions

package.json, src/graphics/viewport.ts, src/index.ejs, src/types/devices/device.ts, src/types/edge.ts, src/types/packet.ts
This PR registers "tap" event handlers in addition to the "click" handlers already installed. This makes the simulator register clicks correctly on mobile devices.
=> fix: use "tap" for mobile compatibility

src/types/devices/device.ts, src/types/devices/host.ts, src/types/devices/router.ts, src/types/devices/switch.ts, src/types/packet.ts
Depends on #134
This PR adds a delay to packet processing on routers and a packet processing counter. When this counter reaches a limit packets start being dropped.
=> feat: make router drop packets if full

src/graphics/right_bar.ts, src/styles/right-bar-buttons.css, src/styles/table.css
Previously, the routing table content would get cut off on smaller screens. Now, it becomes scrollable when needed, ensuring all data remains accessible.
Improved the `right-bar-toggle-button` hover effect by adding a smooth transition and slight zoom effect for better UX.
=> fix: make routing table scrollable on smaller screens

src/packets/ethernet.ts
MacAddresses does not repeat itself
=> fix: MacAddress parse from octets to string correctly

src/graphics/right_bar.ts
Previously, the toggle button was placed inside the `toggle-info-container`, 
which caused inconsistent styling and layout issues in different contexts. 
This fix moves the button outside the container by wrapping both elements  in a separate `div`, ensuring visual consistency across all components.
before:
after:
=> fix: Info-Toggle-Button

src/types/packet.ts
This PR makes ICMP responses yellow again.
=> fix: set payload type when constructing packet

src/context.ts, src/graphics/renderables/device_info.ts, src/types/devices/device.ts, src/types/devices/utils.ts, src/types/graphs/datagraph.ts, src/types/graphs/graph.ts, src/types/graphs/viewgraph.ts, src/types/undo-redo/moves/addRemoveDevice.ts, src/types/undo-redo/moves/addRemoveEdge.ts, src/types/undo-redo/moves/dragDevice.ts, src/types/undo-redo/moves/move.ts, src/types/viewportManager.ts
This PR adds a `Graph` class with the simple logic of storing nodes and edges, and uses it internally in the `DataGraph` class.
=> refactor: move graph functionality to new `Graph` ADT

src/types/graphs/viewgraph.ts
Javascript and Typescript don't have tuple types. When comparing fixed-length arrays, they always return "not equal", because they are objects.
Here we change it to serialize tuples before using them as Map keys
=> fix: serialize tuple before using as key

src/context.ts, src/packets/ethernet.ts, src/packets/ip.ts
This commit corrects the comparison logic in setMacGenerator and setIpGenerator methods to accurately compare MAC and IP addresses byte by byte. 
The previous method relied on array reference comparison, which led to incorrect maximum address detection and subsequent address duplication. The newly introduced helper functions, compareMacs and compareIps, ensure element-wise comparison, preventing duplication by correctly identifying and initializing the maximum address for each generator.
before:
after:
=> Fix MAC and IP address comparison logic in generators

src/graphics/renderables/device_info.ts, src/handlers/undoRedoHandler.ts, src/types/devices/device.ts, src/types/devices/host.ts, src/types/devices/index.ts, src/types/devices/utils.ts, src/types/edge.ts, src/types/graphs/datagraph.ts, src/types/graphs/graph.ts, src/types/graphs/viewgraph.ts, src/types/undo-redo/moves/addRemoveDevice.ts, src/types/undo-redo/moves/addRemoveEdge.ts, src/types/undo-redo/moves/dragDevice.ts, src/types/undo-redo/moves/move.ts, src/types/undo-redo/undoRedoManager.ts, src/types/viewportManager.ts
Related to #119
This PR uses the new `Graph` to specify the interface used on each connection, instead of it being implicitly the ID of the other device.
=> refactor: add edge object to datagraph

src/programs/echo_sender.ts, src/types/devices/device.ts, src/types/devices/host.ts, src/types/devices/networkDevice.ts, src/types/devices/router.ts, src/types/devices/switch.ts, src/types/graphs/datagraph.ts, src/types/packet.ts
This PR continues #157 by moving routing logic to use the new interface fields. It also changes the way packets flow, making devices rewrap packets into frames and send them with `sendRawPacket`, instead of telling the `Packet` object where to go. This should simplify how we do broadcasts.
=> refactor: route packets according to interface in connection

src/context.ts, src/handlers/pauseHandler.ts, src/handlers/speedControlHandler.ts, src/index.ts, src/types/devices/router.ts, src/types/devices/speedMultiplier.ts, src/types/graphs/viewgraph.ts, src/types/packet.ts, src/types/viewportManager.ts
Fixes #125
This PR makes pause and speed handling consistent across the simulation.
- It makes programs stop when simulation is paused
- It makes speed and pauses affect packet processing in routers
It also refactors the `SpeedMultiplier` to present the current speed multiplier as 0 when the simulation is paused and removes the `Packet.isSimulationPaused` field.
=> feat: improve pause and speed handling across simulation

src/types/devices/device.ts, src/types/edge.ts, src/types/graphs/viewgraph.ts
This PR tries to unclutter the view of the canvas by making some edges transparent while selecting devices or edges.
- If the user selects a device, all the edges that are not connected to the device become transparent.
- If the user selects an edge, all the edges become transparent except for the selected one. 
- If no devices or edges are selected, none of the edges are transparent
Maybe we can add a setting to add/remove this functionality, keeping it on by default. Some users might want the edges to be at full opacity all the time. 
closes #165
=> Improve: Make unselected edges transparent

src/types/graphs/graph.ts, src/types/graphs/viewgraph.ts
This PR fixes an issue we had when removing devices where the edges wouldn't come back after undoing the removal.
=> fix: add private helper without datagraph edge removal

src/types/data-devices/dDevice.ts, src/types/edge.ts, src/types/graphs/datagraph.ts, src/types/graphs/viewgraph.ts, src/types/undo-redo/moves/addRemoveDevice.ts, src/types/undo-redo/moves/addRemoveEdge.ts, src/types/view-devices/vDevice.ts, src/types/viewportManager.ts
Depends on #191
Closes #119
This PR adds automatic interface selection for edges, enforcing a maximum number of interfaces for each device (depending on type). It also makes edge selection show information of each interface connection.
Example:
=> feat: show interface on edge information

src/types/edge.ts, src/types/graphs/graph.ts, src/types/graphs/viewgraph.ts
This PR works on #209 to change the way edge visibility is computed. It also moves the DFS algorithm we use to the `Graph` class.
The way edge visibility is computed in this PR is by checking if each device of an edge can reach at least a single visible device. However, when loops exist in the graph, this can lead to false positives, like:
We fix this by doing it iteratively many times, ignoring edges that were marked as invisible in previous iterations.
=> refactor: updateVisibility modifications

src/types/edge.ts, src/types/packet.ts, src/utils/utils.ts
Closes #204
This PR increases the click area for packets and edges. This was done by creating an invisible stroke/circle apart from the visible one.
Setting a non-zero alpha helps for visualizing the true clickable areas for each element:
=> feat: improve click area for packets and edges

src/graphics/renderables/device_info.ts, src/graphics/renderables/switching_table.ts, src/types/data-devices/dSwitch.ts, src/types/graphs/datagraph.ts, src/types/packet.ts, src/types/view-devices/vNetworkDevice.ts, src/types/view-devices/vSwitch.ts, src/utils/constants/alert_constants.ts, src/utils/constants/tooltips_constants.ts
Switching tables have been added, allowing the modification of the port. Currently, the system operates using device IDs. In the future, once the logic supports interface-based management, this functionality will be updated accordingly.
closes #214
=> Feat/switching table UI

src/types/packet.ts
This PR adds an additional color for HTTP packets, which allows us to filter out TCP control segments in the App layer view.
=> feat: differentiate between TCP and HTTP packets

src/utils/constants/router_constants.ts
This PR increases the router queue size and processing speed to 4096 and 1024 respectively, which were reverted on 4c74067.
=> fix: bump up router queue size and processing speed

src/types/network-modules/tcp/tcpState.ts
This PR fixes an issue we had where sometimes the last ACK wasn't sent from the client side on a TCP connection. The issue was fixed by explicitly continuing the main loop until a segment with ACKing the FIN of a connection was sent.
=> fix: ensure we send the last ACK on each TCP connection

src/types/view-devices/vRouter.ts
This PR makes the TTL on each packet decrease on each hop, to simulate the behavior on real networks.
=> feat: decrease TTL on each hop
